### ISSUE TITLE
Question about Process Death

### ISSUE THREAD

**Issue by pablichjenkov** [ukemp/ktor-mqtt#2]
In Android and iOS, the OSes will stop giving you CPU time as soon as the App is placed in the background. How does this library deal with that? Is there any integration with FCM or APN services?

**Comment by ukemp** [comment]
Yes, there can be many reasons for a connection loss in a mobile application and I would expect that to be handled by the application itself and not the library. (Websocket libraries for example would have the same problem.) Overall I think this should be out of scope for a client library like this.

**Comment by pablichjenkov** [comment]
Makes sense thanks. I am closing this one.
